### ISSUE TITLE
SyntaxError: Named export 'withOptions' not found. The requested module 'tailwindcss/plugin.js' is a CommonJS module

### ISSUE THREAD

**Issue by RolginRoman** [Roman86/tailwindcss-scoped-preflight#57] opened 2024-10-21 19:39 UTC
First of all thank you for the plugin, all way it was a bris to work with, but recently we got turned down after migration to package.json type:"module".

**Describe the bug**
Adding the plugin leads to build/serve failing

```
import { withOptions } from 'tailwindcss/plugin.js';

SyntaxError: Named export 'withOptions' not found. The requested module 'tailwindcss/plugin.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from 'tailwindcss/plugin.js';
const { withOptions } = pkg;
```

**To Reproduce**
Code sandbox URL (any platform of your choice): 
https://stackblitz.com/github/RolginRoman/tailwindcss-scoped-demo?file=README.md

The simplest setup of the plugin is here: https://github.com/RolginRoman/tailwindcss-scoped-demo/commit/243827c4b2bc1f526069e7febd0c72005220e476

**Expected behaviour**
Build successfully.  (if possible of course)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac OS but I guess indifferent
 - Browser: Haven't reached there yet

**Additional context**
Bundler: vite@5.4.9
typescript@5.6.3

If I can provide any additional info please let me know!

**Comment by r4m-roman** [comment] 2024-10-21 22:25
@RolginRoman please try v3.4.6 (specify explicitly, as this release is marked as beta, not latest yet). I tested it with your sandbox - the build process is finishing without problems now

**Comment by Roman86** [comment] 2024-10-21 22:25
@RolginRoman please try v3.4.6 (specify explicitly, as this release is marked as beta, not latest yet). I tested it with your sandbox - the build process is finishing without problems now

**Closed** 2024-10-21 22:27 UTC
Labels: bug

**Comment by Roman86** [comment] 2024-10-21 22:28
@RolginRoman  the issue is closed automatically with a commit message. Feel free to re-open if not resolved
